root: true
env:
  es2021: true
  node: true
  "jest/globals": true
extends:
  - "@liatrio/eslint-config"
parserOptions:
  ecmaVersion: 11
rules:
  "security/detect-object-injection": off
overrides:
  - files:
      - "**/*.spec.js"
      - "test/util/jest-setup.js"
    globals:
      fakeLogger: readonly
      fakeOctokit: readonly
      chance: readonly
      when: readonly
    rules:
      "node/no-unpublished-require": off
      max-len: off
  - files:
      - "src/config/default.js"
    rules:
      max-len: off
