on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
#  TAG: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
  TAG: "halp1000.azurecr.io/${{ github.repository }}:${{ github.sha }}"
  IMAGE_NAME: ${{ github.repository }}

name: Deploy

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: halp1000.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.TAG }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-container-action@v1
        id: fa
        with:
          app-name: github-org-protection-service
          image: ${{ env.TAG }}
