on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  workflow_dispatch:

name: Terraform Plan

concurrency:
  group: github-org-protection-service-terraform

jobs:
  plan:
    name: Terraform plan
    runs-on:
      - ubuntu-latest
    needs: validate
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: terraform format check
        working-directory: tf
        run: terraform fmt -check -recursive -diff

      - name: Prepare secrets
        shell: bash
        working-directory: tf
        run: |
          echo TF_SECRETS > secrets.auto.tfvars
          echo TF_BACKEND > backend.tfvars
        env:
            TF_SECRETS: ${{ secrets.TF_SECRETS }}
            TF_BACKEND: ${{ secrets.TF_BACKEND }}

      - name: terraform plan
        run: |
          set -o pipefail
          terraform init -backend-config=backend.tfvars
          terraform validate
          terraform plan -out tfplan.plan
          terraform show -no-color -json tfplan.plan > tfplan.json
        id: plan
        working-directory: tf
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Comment on Pull Request
        uses: liatrio/terraform-change-pr-commenter@main
        with:
          json-file: tf/tfplan.json